# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detection_proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detection_proto.proto',
  package='detection',
  syntax='proto3',
  serialized_options=b'\n\032io.grpc.examples.detectionB\rDetctionProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x64\x65tection_proto.proto\x12\tdetection\"\'\n\x10\x44\x65tectionRequest\x12\x13\n\x0boriginImage\x18\x01 \x01(\x0c\"E\n\x11\x44\x65tectionResponse\x12\x16\n\x0epredictedImage\x18\x01 \x01(\x0c\x12\x18\n\x10predictedResults\x18\x02 \x03(\x05\x32S\n\tDetection\x12\x46\n\x07Predict\x12\x1b.detection.DetectionRequest\x1a\x1c.detection.DetectionResponse\"\x00\x42\x33\n\x1aio.grpc.examples.detectionB\rDetctionProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_DETECTIONREQUEST = _descriptor.Descriptor(
  name='DetectionRequest',
  full_name='detection.DetectionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='originImage', full_name='detection.DetectionRequest.originImage', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=75,
)


_DETECTIONRESPONSE = _descriptor.Descriptor(
  name='DetectionResponse',
  full_name='detection.DetectionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predictedImage', full_name='detection.DetectionResponse.predictedImage', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='predictedResults', full_name='detection.DetectionResponse.predictedResults', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['DetectionRequest'] = _DETECTIONREQUEST
DESCRIPTOR.message_types_by_name['DetectionResponse'] = _DETECTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DetectionRequest = _reflection.GeneratedProtocolMessageType('DetectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONREQUEST,
  '__module__' : 'detection_proto_pb2'
  # @@protoc_insertion_point(class_scope:detection.DetectionRequest)
  })
_sym_db.RegisterMessage(DetectionRequest)

DetectionResponse = _reflection.GeneratedProtocolMessageType('DetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONRESPONSE,
  '__module__' : 'detection_proto_pb2'
  # @@protoc_insertion_point(class_scope:detection.DetectionResponse)
  })
_sym_db.RegisterMessage(DetectionResponse)


DESCRIPTOR._options = None

_DETECTION = _descriptor.ServiceDescriptor(
  name='Detection',
  full_name='detection.Detection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=231,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='detection.Detection.Predict',
    index=0,
    containing_service=None,
    input_type=_DETECTIONREQUEST,
    output_type=_DETECTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTION)

DESCRIPTOR.services_by_name['Detection'] = _DETECTION

# @@protoc_insertion_point(module_scope)
