MODEL:
  DEVICE: "cpu"
  NUM_CLASSES: 5
  BACKBONE:
    OUT_CHANNELS: (512, 1024, 1024, 1024, 1024, 1024)
  PRIORS:
    FEATURE_MAPS: [40, 20, 10, 5, 3, 1]
    STRIDES: [8, 16, 32, 64, 107, 320]
    MIN_SIZES: [21, 45, 99, 153, 207, 261]
    MAX_SIZES: [45, 99, 153, 207, 261, 315]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 6, 4]
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ("coc_770_trainval",)
  TEST: ("coc_770_test",)
SOLVER:
  MAX_ITER: 50000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 24
  LR: 1e-3
